#!/bin/bash

# coded by Frank Simens at 2022 contact frank@simens.dk
# easyaur is a script to use bash to get git clone from the aur from archlinux. easy way to use. copy the file to you /bin folder and you can used it one the hole system.
# Works on Arch BTW


# The skript does clone the git repository, cd into the downloaded folder and run makepkg -si

# set url as arg 1 after the commands
# syntax is ./easyaur.sh arg1 eks. https://aur.archlinux.org/free42.git
url=$1

# print on screen what to get. cancel with CTRL + c
echo Downloading this $url
echo use CTRL + c to cancel

# Wait 10 seconds
COUNT=10
# bash while loop
while [ $COUNT -gt 0 ]; do
        echo -n $COUNT " "
        let COUNT=COUNT-1
        sleep 1
done
echo GO!

# get the last part of the url
echo $url | cut -d "/" -f 4 > /tmp/adir

# save it to a variable
adir=`cat /tmp/adir`

# get the filename for the path after download
echo $adir | cut -d "." -f 1 > /tmp/radir

# save the file name in variable
radir=`cat /tmp/radir`

# clone the link with git klone and do a log file 
git clone $url > gitclonelog
cat gitclonelog

# chdir to the filename as directory
cd $radir 

# install the package. you need need the base-devel and linux-headers installed 
# example sudo pacman -Sy base-devel Linux-headers 
makepkg -si
