#!/bin/bash
# use links to google
# coded by Frank Simens (c) contact frank@simens.dk

# Use this to google from the command line
# syntax is google "the thing you search after"
arg1=$1
arg2=$2
arg3=$3
arg4=$4

if [[ -z $arg1 ]]
then
	
	clear	
	echo """ brug links til at google dine søgninger i terminal, istedet for at have en webbroeser åben.
 smart hvis du kun er på en server. Kopier denne i din /home/bin mappe eler /usr/bin husk at markere script som kørbar
 Syntax du skal bruge er google.sh og det du vil søge efter. EKS google.sh Biler """
else
	clear
	echo search
	links https://www.google.com/search?q=$1+$2+$3+$4 | tee /tmp/loglinks$s
	search=0
   
fi
